language: node_js
node_js:
	- "9"

before_script:
	- "npm install -g gulp-cli"

cache:
	directories:
		- "node_modules"
		- "bower_components"

script: gulp

deploy:
	provider: pages
	skip_cleanup: true
	local_dir: /dist
	github_token: $GITHUB_TOKEN
	on:
		branch: master
